logging:
  level:
    ROOT: DEBUG
    com:
      entando: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
      springframework:
        security: DEBUG


spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
  datasource:
    continue-on-error: true
    initialization-mode: always
    url: jdbc:h2:./entando-data/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


keycloak:
  auth-url: http://hubdev.okd-entando.org/auth
  client-id: germanogiudici-entando-hub-catal-server
  client-secret: d74e6f78-6ffb-4413-a43f-f4b1ea26e204
  ssl-required: none
  auth-server-url: ${keycloak.auth-url}
  bearer-only: true
  credentials:
    secret: ${keycloak.client-secret}
  realm: entando
  resource: ${keycloak.client-id}
  use-resource-role-mappings: true
