server:
  port: 8081
  error:
    whitelabel:
      enabled: false
    path: /error
    include-stacktrace: always
    include-message: always

logging:
  level:
    ROOT: DEBUG
    org:
      springframework:
        security: debug

#https://medium.com/devops-dudes/securing-spring-boot-rest-apis-with-keycloak-1d760b2004e
keycloak:
  auth-url: TO-CHANGE
  client-id: TO-CHANGE
  client-secret: TO-CHANGE
  auth-server-url: ${keycloak.auth-url}
  bearer-only: true
  credentials:
    secret: ${keycloak.client-secret}
  realm: entando
  resource: ${keycloak.client-id}
  use-resource-role-mappings: true

app:
  version: 1
  name: entando-hub-catalog
  security:
    auth-server-url: ${keycloak.auth-server-url}
    realm: ${keycloak.realm}
    client-ui: entando-web


spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
  datasource:
    initialization-mode: never
    url: jdbc:h2:./entando-data/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
